# Generated by Django 4.2.7 on 2023-11-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('city', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('phone_number2', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('appeal', models.CharField(max_length=255, null=True)),
                ('university', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=500)),
                ('languages', models.CharField(max_length=255)),
                ('last_work', models.CharField(max_length=255)),
                ('last_position', models.CharField(max_length=255)),
                ('work_time', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='')),
                ('computer_science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_by_computer_science', to='mainapp.computerscience')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_by_degree', to='mainapp.degree')),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_by_family', to='mainapp.family')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_by_position', to='mainapp.position')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_by_region', to='mainapp.region')),
            ],
        ),
    ]
