# Generated by Django 4.2.7 on 2023-11-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_application_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
