# Generated by Django 4.2.7 on 2023-11-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_application_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.FileField(upload_to='images'),
        ),
    ]
