# Generated by Django 4.2.7 on 2023-11-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_application_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
