# Generated by Django 4.2.7 on 2023-11-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_application_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appeal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='computer_science',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_by_computer_science', to='mainapp.computerscience'),
        ),
        migrations.AlterField(
            model_name='application',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
