# Generated by Django 4.2.7 on 2023-11-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_application_appeal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='application',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone_number2',
        ),
        migrations.RemoveField(
            model_name='application',
            name='university',
        ),
    ]
